name: Update ECSU News Feed

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-22.04  # ✅ Use a stable Ubuntu version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # ✅ Supported version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if feed changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add feed.json
          git commit -m "Update feed" || echo "No changes to commit"
          git push
