name: Update ECSU News Feed

on:
  schedule:
    - cron: "0 12 * * *"  # Every day at 12 PM UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if feed changed
        run: |
          git config --global user.name 'ecsufeedbot'
          git config --global user.email 'ecsufeedbot@example.com'
          git add feed.json
          git commit -m "Auto-update news feed" || echo "No changes to commit"
          git push
